llm:
    name: "qwen-turbo-2024-09-19"
    temperature: 0.7
    api_key: "sk-101e68fd935649dba436f6ffa2b44ede"
embedding:
    name: "BAAI/bge-base-zh-v1.5"
    dim: 768 
    batch_size: 32
rerank:
    name: "BAAI/bge-reranker-large"
    device: "cpu"
milvus:
    host: "localhost" 
    port: 19530
    collection_name: "securilaw_rag"
    retrieve_topk: 100
    window_size: 4
    rerank_topk: 15
pipeline:
    collection_name: "securilaw_rag"
    chunk_size: 500
    retrieve_topk: 8
    


