llm:
    name: "gemini-pro"
    temperature: 0.01
embedding:
    name: "BAAI/bge-base-zh-v1.5"
    dim: 768
rerank:
    name: "BAAI/bge-reranker-large"
milvus:
    host: "localhost"
    port: "19530"
    collection_name: "securilaw_rag"
    retrieve_topk: 100
    window_size: 4
    rerank_topk: 15
pipeline:
    collection_name: "securilaw_rag"
    chunk_size: 500
    retrieve_topk: 8



